<?php
// Serves the daily report generated by scripts/daily_report.php (cron).
// Never calls the Claude API itself, so page loads can't run up a bill.
header('Content-Type: application/json');

$reportFile = __DIR__ . '/cache/daily_report.json';

if (!file_exists($reportFile)) {
    http_response_code(404);
    echo json_encode(['error' => 'No report yet']);
    exit;
}

echo file_get_contents($reportFile);
